class LangManager {
  constructor(ogl) {
    this.ogl = ogl;

    this.en = {
      abbr202: 'SC',
      abbr203: 'LC',
      abbr219: 'PF',
      abbr210: 'SP',
      planets: 'planets',
      ships: 'Ships',
      items: 'Items',
      other: 'Other',
      resources: 'Resources',
      fight: 'Fight',
      noMoonError: 'Error, there is no moon here',
      capacityPicker: 'Resources to send',
      scExpe: 'Small cargo expedition',
      lcExpe: 'Large cargo expedition',
      pfExpe: 'Pathfinder expedition',
      allShipsRes: 'Select all ships (page 1) <br>or all resources (page 2)',
      splitShipsRes: 'Split all ships (page 1) <br>or all resources (page 2)',
      prevFleet: 'Repeat previous fleet',
      required: 'req.',
      reverseAllShipsRes: 'Reverse all selected ships (page 1) <br>or all resources (page 2)',
      nextPlanet: 'Go to next planet',
      prevPlanet: 'Go to previous planet',
      gain: 'Gain',
      timeLimits: 'Day;Week;Month;All',
      spyPosition: 'Spy this position',
      flagTarget: 'Set next target',
      attackCurrentTarget: 'Attack next target',
      noTargetSelected: 'No target selected',
      timerInfo: 'Last refresh',
      blackhole: 'Black hole',
      signalBlackhole: 'Signal a blackhole',
      moreStats: 'More statistics',
      eraseData: 'Erase data',
      defaultView: 'Default view',
      economyView: 'Economy view',
      productionView: 'Production view',
      pinnedView: 'Pinned target',
      targetView: 'Targets list',
      oglConfig: 'OGLight settings',
      defaultShip: 'Default ship',
      defaultMission: 'Default mission',
      autoCollect: 'Collect resources',
      minifyPictures: 'Minify large pictures',
      displayTimers: 'Display refresh timers',
      rentaStats: 'Display stats',
      excludeConso: 'Exclude deut consumption from stats',
      spiesTable: 'Display spies table',
      autoClean: 'Autoclean spies table',
      cleanReport: 'Clean spies reports',
      inFlight: 'In flight',
      linkedMoons: 'Linked moons',
      linkedPlanets: 'Linked planets',
      kofi: 'Do you like OGLight ? Then support me :)',
      wrongTarget: 'Warning, the targeted planet has changed and will be removed from the list !',
      deleteSpyDef: 'Delete spies agaisnt my planets',
      rentaPerDay: 'Mean ($daysd)',
      totalPerDay: 'Mean+prod ($daysd)',
      ignoreRaid: 'Ignore this raid',
      keepOnPlanet: 'to keep on planet',
      switchNameCoords: 'switch coords/names',
      sendResources: 'Send resources',
      sendMissingResources: 'Deduct resources on the planet from the total',
      fleetDetailsName: 'Display ships name in fleet details',
      onPlanets: 'On planets',
      reportFound: 'Top report',
      topReportDetails: 'Top report details',
      playerProfile: 'Player profile',
      rightMenuTooltips: 'Hide right menu tooltips',
      bigShip: 'Use the biggest available ship (expeditions)',
      targetListEnd: 'End of targets list',
      ignoreVacation: 'Hide players in vacation mode (targets list)',
    };

    this.fr = {
      abbr202: 'PT',
      abbr203: 'GT',
      abbr219: 'EC',
      abbr210: 'SP',
      planets: 'planètes',
      ships: 'Vaisseaux',
      other: 'Autre',
      resources: 'Ressources',
      fight: 'Combat',
      noMoonError: "Erreur, il n'y a pas de lune ici",
      capacityPicker: 'Ressources à envoyer',
      scExpe: 'Expedition au PT',
      lcExpe: 'Expedition au GT',
      allShipsRes: 'Selectionner tous les vaisseux (page 1) <br>ou toutes les ressources (page2)',
      splitShipsRes: 'Diviser tous les vaisseux (page 1) <br>ou toutes les ressources (page2)',
      prevFleet: 'Répéter la flotte précédente',
      reverseAllShipsRes: 'Inverser tous les vaisseaux (page 1) <br>ou toutes ressources selectionné(e)s (page 2)',
      nextPlanet: 'Se rendre sur la planète suivante',
      prevPlanet: 'Se rendre sur la planète précédente',
      gain: 'Gain',
      timeLimits: 'Jour;Semaine;Mois;Tout',
      spyPosition: 'Espionner cette position',
      flagTarget: 'Définir la prochaine cible',
      attackCurrentTarget: 'Attaquer la prochaine cible',
      noTargetSelected: 'Aucune cible définie',
      timerInfo: 'Dernier refresh',
      blackhole: 'Trou noir',
      signalBlackhole: 'Signaler un trou noir',
      moreStats: 'Plus de statistiques',
      eraseData: 'Supprimer les données',
      defaultView: 'Vue par défaut',
      economyView: 'Vue économie',
      productionView: 'Vue production',
      pinnedView: 'Cible épinglée',
      targetView: 'Liste des cibles',
      oglConfig: "Configuration d'OGLight",
      defaultShip: 'Vaisseau par défaut',
      defaultMission: 'Mission par défaut',
      autoCollect: 'Collecter les ressources',
      cleanReport: 'Nettoyer les rapports',
      minifyPictures: 'Réduire les grandes images',
      displayTimers: 'Afficher les timers de refresh',
      rentaStats: 'Afficher les statistiques',
      excludeConso: 'Ignorer la conso de deut dans les stats',
      spiesTable: 'Afficher le tableau de RE',
      autoClean: 'Suppression automatique des "mauvais" RE',
      inFlight: 'En vol',
      linkedMoons: 'Lunes associées',
      linkedPlanets: 'Planètes associées',
      kofi: 'Vous aimez OGLight ? Alors soutenez-moi :)',
      wrongTarget: 'Attention, la planète ciblée a changée et va être supprimée de la liste !',
      deleteSpyDef: 'Supprimer les espionnages contre mes planètes',
      rentaPerDay: 'Moyenne ($daysj)',
      totalPerDay: 'Moyenne+prod ($daysj)',
      ignoreRaid: 'Ignorer ce raid',
      keepOnPlanet: 'à garder sur la planète',
      switchNameCoords: 'alterner coords/noms',
      sendResources: 'Envoyer les ressources',
      sendMissingResources: 'Déduire les ressources à quai',
      fleetDetailsName: 'Afficher le nom des vaisseaux',
      onPlanets: 'A quai',
      reportFound: 'Meilleur rapport',
      topReportDetails: 'Détails du rapport',
      playerProfile: 'Profil de la cible',
      rightMenuTooltips: 'Cacher les tooltips du menu de droite',
      bigShip: 'Utiliser le plus gros vaisseau disponible (expeditions)',
      targetListEnd: 'Fin de la liste de cibles',
      ignoreVacation: 'Cacher les joueurs en MV (liste de cibles)',
    };

    this.gr = {
      abbr202: 'μΜ',
      abbr203: 'ΜΜ',
      abbr219: 'PF',
      abbr210: 'ΚΣ',
      planets: 'Πλανήτες',
      ships: 'Πλοία',
      items: 'Αντικέιμενα',
      other: 'Λοιπά',
      resources: 'Πόροι',
      fight: 'Μάχες',
      noMoonError: 'Σφάλμα, δεν υπάρχει φεγγάρι εδώ',
      capacityPicker: 'Πόροι για αποστολή',
      scExpe: 'Αποστολή με μικρά μεταγωγικά',
      lcExpe: 'Αποστολή με μεγάλα μεταγωγικά',
      allShipsRes: 'Επιλέξτε όλα τα πλοία (σελίδα 1) ή όλους τους πόρους (σελίδα 3))',
      splitShipsRes: 'Διαχωρίστε όλα τα πλοία (σελίδα 1) ή όλους τους πόρους (σελίδα 3) με την επιλεγμένη τιμή (2-9)',
      prevFleet: 'Επάληψη προηγούμενου στόλου',
      required: 'Απαιτ.',
      reverseAllShipsRes: 'Αντιστρέψτε όλα τα επιλεγμένα πλοία (σελίδα 1) ή όλους τους πόρους (σελίδα 3)',
      nextPlanet: 'Πηγαίνετε στον επόμενο πλανήτη',
      gain: 'Κέρδος',
      timeLimits: 'Ημέρα;Εβδομάδα;Μήνας;Σύνολο',
      spyPosition: 'Κατασκοπεύστε αυτήν τη θέση',
      flagTarget: 'Ορίστε τον επόμενο στόχο',
      attackCurrentTarget: 'Επίθεση στον επόμενο στόχο',
      noTargetSelected: 'Δεν έχει επιλεγεί στόχος',
      timerInfo: 'Τελευταία ανανέωση',
      blackhole: 'Μαύρη τρύπα',
      signalBlackhole: 'Σημειώστε μια μαύρη τρύπα',
      moreStats: 'Επιπλέον στατιστικά',
      eraseData: 'Διαγραφή δεδομένων',
      defaultView: 'Προεπιλεγμένη προβολή',
      economyView: 'Προβολή οικονομίας',
      productionView: 'Προβολή παραγωγής',
      pinnedView: 'Καρφιτσωμένος στόχος',
      targetView: 'Λίστα στόχων',
      oglConfig: 'OGLight ρυθμίσεις',
      defaultShip: 'Σκάφος προεπιλογής',
      defaultMission: 'Προεπιλεγμένη μετακίνηση',
      autoCollect: 'Συλλέξτε πόρους',
      minifyPictures: 'Ελαχιστοποίηση μεγάλων εικόνων',
      displayTimers: 'Προβολή χρονόμετρων ανανέωσης',
      rentaStats: 'Στατιστικά εσόδων',
      excludeConso: 'Εξαίρεση της κατανάλωσης δευτερίου από τα στατιστικά',
      spiesTable: 'Εμφάνιση πίνακα κατασκοπειών',
      autoClean: 'Αυτόματη εκκαθάριση πίνακα κατασκοπειών',
      inFlight: 'Εν πτήση',
      linkedMoons: 'Συνδεδεμένα φεγγάρια',
      linkedPlanets: 'Συνδεδεμένοι πλανήτες',
      kofi: 'Σας αρέσει το OGLight ; Τότε υποστηρίξτε με :)',
      wrongTarget: 'Προειδοποίηση, ο στοχευμένος πλανήτης δεν υπάρχει πλέον και θα αφαιρεθεί από τη λίστα!',
      deleteSpyDef: 'Διαγραφή κατασκ. αναφορών των πλανητών μου',
      rentaPerDay: 'Mean ($daysd)',
      totalPerDay: 'Mean+prod ($daysd)',
      ignoreRaid: 'Αγνόησε αυτή τη μάχη',
      keepOnPlanet: 'Να παραμείνουν στον πλανήτη',
      switchNameCoords: 'Εναλλαγή συντεταγμένων / ονομάτων',
      sendResources: 'Αποστολή πόρων',
      sendMissingResources: 'Αφαιρέστε τους πόρους στον πλανήτη από το σύνολο',
    };
  }

  // get text by key. priority : library > local key > english key
  getText(key) {
    if (this[this.ogl.universe.lang] && this[this.ogl.universe.lang][key]) return this[this.ogl.universe.lang][key];
    else if (this.ogl.db.loca[key]) return this.ogl.db.loca[key];
    else if (this.ogl.db.ships[key]?.name) return this.ogl.db.ships[key].name;
    else if (this.en[key]) return this.en[key];
    else return 'TEXT_NOT_FOUND';
  }
}

export default LangManager;
